# Generated by Django 5.1.3 on 2024-11-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_content_news_description_news_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('gender', models.CharField(choices=[('M', 'Мальчик'), ('F', 'Девочка')], max_length=1, verbose_name='Пол')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='animal_photos/', verbose_name='Фото')),
            ],
        ),
    ]
