# Generated by Django 5.1.3 on 2024-11-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_animal_photo_animalphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalphoto',
            name='photo',
            field=models.ImageField(upload_to='media/animal_photos/', verbose_name='Фото'),
        ),
    ]
