# Generated by Django 5.1.3 on 2024-12-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalphoto',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='animalphoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='animal_photos/', verbose_name='Фото'),
        ),
    ]
